blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://cwiki.apache.org/confluence/display/HUDI/FAQ
    about: Do checkout frequently asked questions before filing an issue.
  - name: Hudi JIRA Board
    url: https://issues.apache.org/jira/projects/HUDI
    about: Reporting bugs on JIRA board helps us better track the issue. But it is not manditory as of now. 
