/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package hadoop.small.files.merger

import java.util.Calendar

import com.databricks.spark.avro._
import hadoop.small.files.merger.utils.{CommandLineArgs, CommandLineArgsParser, HDFSUtils}
import org.apache.spark.sql.SparkSession


object HDFSFileMerger extends App {

  val commandLine = new CommandLineArgsParser

  commandLine
    .parser
    .parse(args, new CommandLineArgs) match {
    case Some(config) => {

      val sparkSession: SparkSession = SparkSession.builder().getOrCreate()
      val mergeFiles = new MergeFiles(sparkSession,config)
      mergeFiles.start()

    }
    case _ => commandLine.parser.renderTwoColumnsUsage
  }

}
