name: Mark stale issues

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue had no activity for at least three months. It's subject to automatic issue closing if there is no activity in the next 5 days."
        stale-issue-label: "inactive"
        days-before-stale: 1
        days-before-close: 5
